### ISSUE TITLE
Header anchor IDs should be semantic and suitable for permalinks

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-docs#45] opened 2018-09-01 17:31 UTC
For instance: `https://kolibri.readthedocs.io/en/latest/install.html#id8`

In this example, `#id8` is enumerated, and adding another heading before will change it into `#id9`, thus breaking outside references.

If it's offered by Sphinx, we should find a way to change these links so that they are permanent. Otherwise a lot of references from Community support etc. will be broken.

If this doesn't work, a nice alternative/compromise would be that we simply don't link to specific sections with anchor links that are non-permanent.

**Comment by indirectlylit** [comment] 2018-09-04 15:43
sorry, could you clarify what the expected behavior is?

**Comment by benjaoming** [comment] 2018-09-04 18:16
Yup @indirectlylit, updated the description

**Comment by indirectlylit** [comment] 2018-09-04 23:36
Got it - thanks. Agreed, the ID should be derived from the header text

**Comment by radinamatic** [comment] 2018-09-07 01:06
I believe it's happening because the page contains multiple 3rd level headings with the same name: Compatibility, Install, Uninstall, Upgrade. When a heading/subheading cannot be uniquely resolved as `page.html#heading`, it defaults to resolving as a numbered `id` one.

I've been researching solutions, but there does not seem to be a suitable one. I could try to create a more explicit header links, but they will not be included in the TOC ([example](https://stackoverflow.com/questions/23530950/how-to-set-custom-headerlink)). Not many solutions offered for customizing the [TOC directive](http://www.sphinx-doc.org/en/stable/markup/toctree.html) with Sphinx. 

Another option would be to make headings unique: _Compatibility on Windows, Install on Windows, Uninstall on Windows, Upgrade on Windows_ but I don't like the sound of it, it's repetitive... 😕

**Comment by benjaoming** [comment] 2018-09-07 15:20
@radinamatic thanks for investigating - yup, let's not compromise the wording of the headers themselves :)

**Comment by radinamatic** [comment] 2019-06-18 02:18
Actually, I would prefer to keep this open. 

I've been working, on and off, to find a solution for this, but it is a major undertaking as it would imply the restructure of the way topics are presented: instead of using the `.. include` directive, to form one long page for the first level TOC items, subtopics would be loaded as single pages and navigation would mean more clicking to <kbd>Next</kbd> and <kbd>Previous</kbd> buttons, instead of scrolling the page up and down.

These shorter more granular pages would ideally allow fully semantic permalinks, even with multiple similar headings, for example: 
- `https://kolibri.readthedocs.io/en/latest/install/linux.html#upgrade`
- `https://kolibri.readthedocs.io/en/latest/install/windows.html#upgrade`

**Comment by ivanistheone** [comment] 2019-06-26 02:33
Wow @radinamatic this is a great initiative to use smaller pages rather than long scrollable ones!

Smaller pages and "permanent" URLs would make linking to the docs from forums, emails, other docs, etc super useful, in particular when using "deep links" that include the exact link anchor on the page, like #import-content-into-kolibri on the manage kolibri page, to sent users to read more details about a particular step.

E.g. "To learn more about importing content in Kolibri see
 https://kolibri.readthedocs.io/en/latest/manage.html#import-content-into-kolibri for the existing docs "



```
___________________________
```


Since we're on the topic of permalinks here is a related docs improvement suggestion:

Problem: Several times in the past I've wanted to send a link to the kolibri docs about "importing using a token" and I end up having to explain because the #import-content-into-kolibri anchor is not specific enough.

Proposed solution: split this section into three separate subsections with their own anchor (sphynx auto-anchor from title)


#import-content-into-kolibri -- stays as containing heading (also preserves any existing links),
then have three subsections A B C:

---


A. `#import-public-channel-into-kolibri` -- for steps 1 through 6

----

B. `#import-unlisted-channel-into-kolibri` -- for steps 7 through 10:

7. If you need to import content from a private/unlisted channel, click on Try adding the token link above the channel list.

8. Enter the channel token/ID received from the channel curator on Kolibri Studio.
Use the text input field to enter channel token in order to import from an unlisted channel

9. Click CONFIRM to unlock channel, or CANCEL to exit.

10. Proceed to select and import channel topics and resources as for the public channels.
Unlisted or private channels in the list are indicated with the lock_openUnlisted channel icon.


---

C. `#updating-channels`  --- for step 11.   (i.e. OPTIONS > Import mode)

---




The proposed change would allow to deep link to A, B, and C individually (at the cost of some repetition between A and B).

**Comment by indirectlylit** [comment] 2019-06-26 19:16
A minor note: I find that the `.. include` directive increases friction for making occasional drive-by updates. It's easier when `.html` files map directly to their `.rst` source files.

**Comment by benjaoming** [comment] 2019-07-01 13:55
I'd also like to add the observation that I haven't seen this `.. include subsection.rst` pattern in other Sphinx projects.

**Comment by benjaoming** [comment] 2019-12-14 15:27
using the `.. include subsection.rst` also makes analytics harder, since we don't know very accurately which section people reads (anchor links do not register).

**Closed as completed** 2019-12-20 21:49 UTC
